// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient, fetchClient } from '@/module/core'
import type { operations, components } from '@/shared/types/api'

import { useInfiniteQuery } from "@tanstack/react-query"
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export type useUserGetAddressesResponse = operations['UserController_getAddresses']['responses'][200]['content']['application/json'];

export const useUserGetAddresses = (
        fetchOptions?: FetchOptions<operations['UserController_getAddresses']>,
        options?: Parameters<OpenapiQueryClient<'get', '/user/addresses/{userId}'>['useQuery']>['3']
      ) => {
    // @ts-ignore
    return apiClient.useQuery('get', '/user/addresses/{userId}' as const, fetchOptions, options)
  }
