// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient, fetchClient } from '@/module/core'
import type { operations, components } from '@/shared/types/api'

import { useInfiniteQuery } from "@tanstack/react-query"
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export type useUserFindOneResponse = operations['UserController_findOne']['responses'][200]['content']['application/json'];

export const useUserFindOne = (
        fetchOptions?: FetchOptions<operations['UserController_findOne']>,
        options?: Parameters<OpenapiQueryClient<'get', '/user/{id}'>['useQuery']>['3']
      ) => {
    // @ts-ignore
    return apiClient.useQuery('get', '/user/{id}' as const, fetchOptions, options)
  }
