// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient, fetchClient } from '@/module/core'
import type { operations, components } from '@/shared/types/api'

import { useInfiniteQuery } from "@tanstack/react-query"
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export type useProductCategoryFindOneResponse = operations['ProductCategoryController_findOne']['responses'][200]['content']['application/json'];

export const useProductCategoryFindOne = (
        fetchOptions?: FetchOptions<operations['ProductCategoryController_findOne']>,
        options?: Parameters<OpenapiQueryClient<'get', '/product-category/{id}'>['useQuery']>['3']
      ) => {
    // @ts-ignore
    return apiClient.useQuery('get', '/product-category/{id}' as const, fetchOptions, options)
  }
