// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient, fetchClient } from '@/module/core'
import type { operations, components } from '@/shared/types/api'

import { useInfiniteQuery } from "@tanstack/react-query"
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export type useProductCategoryFindAllResponse = operations['ProductCategoryController_findAll']['responses'][200]['content']['application/json'];

export const useProductCategoryFindAll = (
        fetchOptions?: FetchOptions<operations['ProductCategoryController_findAll']>,
        options?: Parameters<OpenapiQueryClient<'get', '/product-category'>['useQuery']>['3']
      ) => {
    // @ts-ignore
    return apiClient.useQuery('get', '/product-category' as const, fetchOptions, options)
  }
