// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient, fetchClient } from '@/module/core'
import type { operations, components } from '@/shared/types/api'

import { useInfiniteQuery } from "@tanstack/react-query"
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export type useProductsFindAllResponse = operations['ProductsController_findAll']['responses'][200]['content']['application/json'];

export const useProductsFindAll = (
        fetchOptions?: FetchOptions<operations['ProductsController_findAll']>,
        options?: Parameters<OpenapiQueryClient<'get', '/products'>['useQuery']>['3']
      ) => {
    // @ts-ignore
    return apiClient.useQuery('get', '/products' as const, fetchOptions, options)
  }

export const useProductsFindAllInfinite = (
        options?: Parameters<typeof useInfiniteQuery<useProductsFindAllResponse>>[0]
      ) => {
       return useInfiniteQuery<useProductsFindAllResponse>({
    queryKey: ['get', '/products'],
    initialPageParam: 1,
    getNextPageParam: (lastPage) => {
      if (lastPage.page < lastPage.totalPage) {
        return lastPage.page + 1
      }
    },
    queryFn: ({ pageParam = 1 }) => {
      return fetchClient
        .GET('/products', {
          params: { query: { page: Number(pageParam) } },
        })
        .then((res) => res.data as useProductsFindAllResponse)
        .catch((err) => {
          throw err
        })
    },
    ...options
  })
  }
