// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient, fetchClient } from '@/module/core'
import type { operations, components } from '@/shared/types/api'

import { useInfiniteQuery } from "@tanstack/react-query"
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export type useCartGetCartResponse = operations['CartController_getCart']['responses'][200]['content']['application/json'];

export const useCartGetCart = (
        fetchOptions?: FetchOptions<operations['CartController_getCart']>,
        options?: Parameters<OpenapiQueryClient<'get', '/cart'>['useQuery']>['3']
      ) => {
    // @ts-ignore
    return apiClient.useQuery('get', '/cart' as const, fetchOptions, options)
  }
