// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient, fetchClient } from '@/module/core'
import type { operations, components } from '@/shared/types/api'

import { useInfiniteQuery } from "@tanstack/react-query"
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export const useCartCheckoutCart = (options?: Parameters<OpenapiQueryClient<'post', '/cart/{sessionId}/checkout'>['useMutation']>['2']) => {
      // @ts-ignore
    return apiClient.useMutation('post', '/cart/{sessionId}/checkout' as const, options)
  }
