/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_findAll"];
        put?: never;
        post: operations["ProductsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["ProductsController_remove"];
        options?: never;
        head?: never;
        patch: operations["ProductsController_update"];
        trace?: never;
    };
    "/products/{id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProductsController_addVariant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/variants/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["ProductsController_updateVariant"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductCategoryController_findAll"];
        put?: never;
        post: operations["ProductCategoryController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product-category/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductCategoryController_findOne"];
        put?: never;
        post?: never;
        delete: operations["ProductCategoryController_remove"];
        options?: never;
        head?: never;
        patch: operations["ProductCategoryController_update"];
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_findAll"];
        put?: never;
        post: operations["UserController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UserController_findOne"];
        put?: never;
        post?: never;
        delete: operations["UserController_remove"];
        options?: never;
        head?: never;
        patch: operations["UserController_update"];
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrderController_findAll"];
        put?: never;
        post: operations["OrderController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrderController_findOne"];
        put?: never;
        post?: never;
        delete: operations["OrderController_remove"];
        options?: never;
        head?: never;
        patch: operations["OrderController_update"];
        trace?: never;
    };
    "/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PaymentController_createPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentController_getPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/{orderId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentController_syncPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CartController_getCart"];
        put?: never;
        post?: never;
        delete: operations["CartController_clearCart"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CartController_addToCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["CartController_removeCartItem"];
        options?: never;
        head?: never;
        patch: operations["CartController_updateCartItem"];
        trace?: never;
    };
    "/cart/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CartController_mergeGuestCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CartController_checkoutCart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CartController_completeCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateProductDto: {
            name: string;
            description: string;
            categoryId?: number;
        };
        ProductVariant: {
            id: number;
            name: string;
            price: number;
            product: components["schemas"]["Product"];
            stock_quantity: number;
        };
        Product: {
            id: number;
            name: string;
            description: string;
            categoryId: number;
            category: components["schemas"]["ProductCategory"];
            variants: components["schemas"]["ProductVariant"][];
        };
        ProductCategory: {
            id: number;
            name: string;
            description: string;
            products: components["schemas"]["Product"][];
        };
        ProductDto: {
            /** @example 1 */
            id: number;
            /** @example Sample Product */
            name: string;
            /** @example This is a sample product description. */
            description: string;
            category: {
                id: number;
                name: string;
                description: string;
            };
        };
        FindAllProductDto: {
            data: components["schemas"]["ProductDto"][];
            totalRecords: number;
            totalPage: number;
            page: number;
            limit: number;
        };
        VariantDto: {
            id: number;
            name: string;
            price: number;
            stock_quantity: number;
        };
        FindOneProductDto: {
            id: number;
            name: string;
            description: string;
            category: {
                id: number;
                name: string;
                description: string;
            };
            variants: components["schemas"]["VariantDto"][];
        };
        UpdateProductDto: Record<string, never>;
        CreateVariantDto: {
            name: string;
            price: number;
            productId: number;
        };
        CreateProductCategoryDto: {
            name: string;
            description: string;
        };
        UpdateProductCategoryDto: Record<string, never>;
        CreateUserDto: Record<string, never>;
        GetProfileDto: {
            id: number;
            username: string;
            email: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        User: {
            id: number;
            username: string;
            firstname: string;
            lastname: string;
            email: string;
            phone: string;
            password: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            orders: components["schemas"]["Order"][];
        };
        OrderItem: {
            id: number;
            order: components["schemas"]["Order"];
            productVariant: components["schemas"]["ProductVariant"];
            productVariantId: number;
            quantity: number;
            price: number;
        };
        Order: {
            id: string;
            user: components["schemas"]["User"];
            orderItems: components["schemas"]["OrderItem"][];
            /** Format: date-time */
            orderDate: string;
            totalAmount: number;
            /** @enum {string} */
            order_status: "pending" | "pending_payment" | "payment_received" | "order_confirmed" | "failed" | "expired" | "awaiting_shipment" | "on_hold" | "awaiting_pickup" | "completed" | "cancelled";
        };
        UpdateUserDto: Record<string, never>;
        SignupDto: {
            username: string;
            firstname: string;
            lastname: string;
            /** Format: email */
            email: string;
            phone: string;
            password: string;
        };
        SignupResponseDto: {
            id: number;
            username: string;
            firstname: string;
            lastname: string;
            email: string;
            phone: string;
            password: string;
        };
        LoginResponseDto: {
            token: string;
            refreshToken: string;
            user: components["schemas"]["SignupResponseDto"];
        };
        LoginDto: {
            username: string;
            password: string;
        };
        RefreshTokenDto: {
            refreshToken: string;
        };
        CreateOrderDto: {
            /** @description The ID of the user placing the order */
            userId: number;
        };
        /** @enum {string} */
        OrderStatus: "pending" | "pending_payment" | "payment_received" | "order_confirmed" | "failed" | "expired" | "awaiting_shipment" | "on_hold" | "awaiting_pickup" | "completed" | "cancelled";
        GetPaymentDto: {
            /** @description HTTP status code equivalent for the transaction result. */
            status_code: string;
            /**
             * Format: uuid
             * @description Unique ID for the transaction (UUID format).
             */
            transaction_id: string;
            /** @description The gross amount of the transaction. */
            gross_amount: number;
            /**
             * @description Currency code in ISO 4217 format.
             * @enum {string}
             */
            currency: "USD" | "EUR" | "IDR";
            /**
             * Format: uuid
             * @description Unique ID for the merchant's order (UUID format).
             */
            order_id: string;
            /**
             * @description The payment method used.
             * @enum {string}
             */
            payment_type: "card" | "bank_transfer" | "e_wallet" | "other";
            /** @description Hashed signature for verifying data integrity. */
            signature_key: string;
            /**
             * @description The final status of the transaction.
             * @enum {string}
             */
            transaction_status: "capture" | "pending" | "success" | "failed" | "settlement" | "failure" | "cancel" | "deny" | "expire";
            /**
             * @description Result of the fraud detection analysis.
             * @enum {string}
             */
            fraud_status: "accept" | "deny" | "challenge";
            /** @description A human-readable message about the status. */
            status_message: string;
            /** @description The unique identifier for the merchant. */
            merchant_id: string;
            /** @description Type of transaction processing. */
            transaction_type: string;
            /** @description The party that issued the payment instrument. */
            issuer: string;
            /** @description The payment processor that acquired the transaction. */
            acquirer: string;
            /**
             * Format: date-time
             * @description The time the transaction was initiated.
             */
            transaction_time: string;
            /**
             * Format: date-time
             * @description The time the transaction was successfully settled.
             */
            settlement_time: string;
            /**
             * Format: date-time
             * @description The time the payment request would have expired.
             */
            expiry_time: string;
            /** @description Redirect URL for completing the payment. */
            payment_url?: string | null;
        };
        OrderDto: {
            id: string;
            user: components["schemas"]["User"];
            orderItems: components["schemas"]["OrderItem"][];
            /** Format: date-time */
            orderDate: string;
            totalAmount: number;
            order_status: components["schemas"]["OrderStatus"];
            payment?: components["schemas"]["GetPaymentDto"][] | null;
        };
        FindAllOrderDto: {
            data: components["schemas"]["OrderDto"][];
            totalRecords: number;
            totalPage: number;
            page: number;
            limit: number;
        };
        FindOneOrderDto: {
            payment: components["schemas"]["GetPaymentDto"] | null;
            id: string;
            /** Format: date-time */
            orderDate: string;
            orderItems: components["schemas"]["OrderItem"][];
            /** @enum {string} */
            order_status: "pending" | "pending_payment" | "payment_received" | "order_confirmed" | "failed" | "expired" | "awaiting_shipment" | "on_hold" | "awaiting_pickup" | "completed" | "cancelled";
            totalAmount: number;
        };
        UpdateOrderDto: Record<string, never>;
        CreatePaymentCustomerDto: {
            first_name: string;
            last_name: string;
            email: string;
            phone: string;
        };
        CreatePaymentRequestDto: {
            order_id: string;
            amount: number;
            customer: components["schemas"]["CreatePaymentCustomerDto"];
            description?: string;
        };
        CreatePaymentResponseDto: {
            success: boolean;
            transaction_token?: string;
            redirect_url?: string;
            order_id: string;
            message?: string;
            error?: string;
        };
        Cart: {
            id: number;
            userId: number;
            items: components["schemas"]["CartItem"][];
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            sessionId: string;
        };
        CartItem: {
            id: number;
            cartId: number;
            cart: components["schemas"]["Cart"];
            productVariantId: number;
            productVariant: components["schemas"]["ProductVariant"];
            quantity: number;
            price: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AddToCartDto: {
            productVariantId: number;
            quantity: number;
            sessionId?: string;
        };
        UpdateCartItemDto: {
            quantity: number;
        };
        CheckoutCartDto: {
            items: components["schemas"]["CartItem"][];
            paymentMethods: string[];
        };
        CompleteCheckoutDto: {
            paymentMethod: string;
        };
        CompleteCheckoutResponseDto: {
            orderId: string;
            transactionToken?: string;
            redirectUrl?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type CreateProductDto = components['schemas']['CreateProductDto'];
export type ProductVariant = components['schemas']['ProductVariant'];
export type Product = components['schemas']['Product'];
export type ProductCategory = components['schemas']['ProductCategory'];
export type ProductDto = components['schemas']['ProductDto'];
export type FindAllProductDto = components['schemas']['FindAllProductDto'];
export type VariantDto = components['schemas']['VariantDto'];
export type FindOneProductDto = components['schemas']['FindOneProductDto'];
export type UpdateProductDto = components['schemas']['UpdateProductDto'];
export type CreateVariantDto = components['schemas']['CreateVariantDto'];
export type CreateProductCategoryDto = components['schemas']['CreateProductCategoryDto'];
export type UpdateProductCategoryDto = components['schemas']['UpdateProductCategoryDto'];
export type CreateUserDto = components['schemas']['CreateUserDto'];
export type GetProfileDto = components['schemas']['GetProfileDto'];
export type User = components['schemas']['User'];
export type OrderItem = components['schemas']['OrderItem'];
export type Order = components['schemas']['Order'];
export type UpdateUserDto = components['schemas']['UpdateUserDto'];
export type SignupDto = components['schemas']['SignupDto'];
export type SignupResponseDto = components['schemas']['SignupResponseDto'];
export type LoginResponseDto = components['schemas']['LoginResponseDto'];
export type LoginDto = components['schemas']['LoginDto'];
export type RefreshTokenDto = components['schemas']['RefreshTokenDto'];
export type CreateOrderDto = components['schemas']['CreateOrderDto'];
export type OrderStatus = components['schemas']['OrderStatus'];
export type GetPaymentDto = components['schemas']['GetPaymentDto'];
export type OrderDto = components['schemas']['OrderDto'];
export type FindAllOrderDto = components['schemas']['FindAllOrderDto'];
export type FindOneOrderDto = components['schemas']['FindOneOrderDto'];
export type UpdateOrderDto = components['schemas']['UpdateOrderDto'];
export type CreatePaymentCustomerDto = components['schemas']['CreatePaymentCustomerDto'];
export type CreatePaymentRequestDto = components['schemas']['CreatePaymentRequestDto'];
export type CreatePaymentResponseDto = components['schemas']['CreatePaymentResponseDto'];
export type Cart = components['schemas']['Cart'];
export type CartItem = components['schemas']['CartItem'];
export type AddToCartDto = components['schemas']['AddToCartDto'];
export type UpdateCartItemDto = components['schemas']['UpdateCartItemDto'];
export type CheckoutCartDto = components['schemas']['CheckoutCartDto'];
export type CompleteCheckoutDto = components['schemas']['CompleteCheckoutDto'];
export type CompleteCheckoutResponseDto = components['schemas']['CompleteCheckoutResponseDto'];
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    ProductsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindAllProductDto"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindAllProductDto"];
                };
            };
        };
    };
    ProductsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    ProductsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindOneProductDto"];
                };
            };
            /** @description Product not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProductsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_addVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProductsController_updateVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVariantDto"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductVariant"];
                };
            };
        };
    };
    ProductCategoryController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCategory"][];
                };
            };
        };
    };
    ProductCategoryController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductCategoryDto"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProductCategoryController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ProductCategoryController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductCategoryController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductCategoryDto"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    UserController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UserController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetProfileDto"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UserController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    UserController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UserController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupDto"];
            };
        };
        responses: {
            /** @description User signup */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description User login */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            /** @description Refresh token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_findAll: {
        parameters: {
            query?: {
                page?: number;
                take?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindAllOrderDto"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindAllOrderDto"];
                };
            };
        };
    };
    OrderController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    OrderController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindOneOrderDto"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindOneOrderDto"];
                };
            };
        };
    };
    OrderController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderDto"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    PaymentController_createPayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaymentRequestDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePaymentResponseDto"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePaymentResponseDto"];
                };
            };
        };
    };
    PaymentController_getPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPaymentDto"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    PaymentController_syncPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPaymentDto"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPaymentDto"];
                };
            };
        };
    };
    CartController_getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    CartController_clearCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    CartController_addToCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddToCartDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    CartController_removeCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    CartController_updateCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartItemDto"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    CartController_mergeGuestCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
        };
    };
    CartController_checkoutCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutCartDto"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutCartDto"];
                };
            };
        };
    };
    CartController_completeCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteCheckoutDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteCheckoutResponseDto"];
                };
            };
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteCheckoutResponseDto"];
                };
            };
        };
    };
}
