// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient, fetchClient } from '@/module/core'
import type { operations, components } from '@/shared/types/api'

import { useInfiniteQuery } from "@tanstack/react-query"
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export type useAppGetHelloResponse = operations['AppController_getHello']['responses'][200]['content']['application/json'];

export const useAppGetHello = (
        fetchOptions?: FetchOptions<operations['AppController_getHello']>,
        options?: Parameters<OpenapiQueryClient<'get', '/'>['useQuery']>['3']
      ) => {
    // @ts-ignore
    return apiClient.useQuery('get', '/' as const, fetchOptions, options)
  }
