// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient, fetchClient } from '@/module/core'
import type { operations, components } from '@/shared/types/api'

import { useInfiniteQuery } from "@tanstack/react-query"
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export type usePaymentGetPaymentResponse = operations['PaymentController_getPayment']['responses'][200]['content']['application/json'];

export const usePaymentGetPayment = (
        fetchOptions?: FetchOptions<operations['PaymentController_getPayment']>,
        options?: Parameters<OpenapiQueryClient<'get', '/payment/{orderId}'>['useQuery']>['3']
      ) => {
    // @ts-ignore
    return apiClient.useQuery('get', '/payment/{orderId}' as const, fetchOptions, options)
  }
