// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient, fetchClient } from '@/module/core'
import type { operations, components } from '@/shared/types/api'

import { useInfiniteQuery } from "@tanstack/react-query"
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export type usePaymentSyncPaymentResponse = operations['PaymentController_syncPayment']['responses'][200]['content']['application/json'];

export const usePaymentSyncPayment = (
        fetchOptions?: FetchOptions<operations['PaymentController_syncPayment']>,
        options?: Parameters<OpenapiQueryClient<'get', '/payment/{orderId}/sync'>['useQuery']>['3']
      ) => {
    // @ts-ignore
    return apiClient.useQuery('get', '/payment/{orderId}/sync' as const, fetchOptions, options)
  }
